FROM dmcginnis/fedora-node-chrome

MAINTAINER Dominic McGinnis, dominic.mcginnis@elliemae.com

ENV APP_DIR /usr/src/app

# ems uses a node module that requires tar, bzip2 and gcc
RUN dnf install -y tar bzip2 gcc-c++

# Copy over private npmrc
ADD .npmrc /root/.npmrc

# Add EMS CLI
RUN npm install -g @elliemae/em-swift-cli@3.0.3 ; exit 0;
RUN npm install -g tsd ; exit 0;

# Reset root user password
RUN echo 'root:bobafett' | chpasswd

# Add jenkins and systemd-bus-proxy (for cloudbees) users and grant sudo access
RUN useradd -d /home/jenkins_home -u 1000 -p jenkins -m -s /bin/bash jenkins ; exit 0;
RUN useradd -d /home/systemd-bus-proxy -u 996 -p systemd-bus-proxy -m -s /bin/bash systemd-bus-proxy ; exit 0;
RUN usermod jenkins -a -G wheel ; exit 0;
RUN usermod systemd-bus-proxy -a -G wheel ; exit 0;
RUN echo 'jenkins   ALL=(ALL:ALL) ALL' >> /etc/sudoers
RUN echo 'systemd-bus-proxy   ALL=(ALL:ALL) ALL' >> /etc/sudoers
RUN echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN chmod -R 777 ~
